CREATE TABLE Appointments (
        AppointmentId INT IDENTITY(1,1) PRIMARY KEY,
        PatientId INT NOT NULL,
        DoctorId INT NOT NULL,
        AppointmentDate DATE NOT NULL,
        AppointmentTime TIME NOT NULL,
        EndTime TIME NOT NULL,
        Status NVARCHAR(50) NOT NULL DEFAULT 'Pending',
        ReasonForVisit NVARCHAR(500),
        Symptoms NVARCHAR(1000),
        Diagnosis NVARCHAR(MAX),
        Prescription NVARCHAR(MAX),
        Notes NVARCHAR(MAX),
        CancellationReason NVARCHAR(500),
        IsRecommended BIT DEFAULT 0,
        RecommendationScore DECIMAL(5,2),
        CreatedAt DATETIME2 DEFAULT GETDATE(),
        UpdatedAt DATETIME2 DEFAULT GETDATE(),
        CompletedAt DATETIME2,
        CancelledAt DATETIME2,
        FOREIGN KEY (PatientId) REFERENCES Patients(PatientId),
        FOREIGN KEY (DoctorId) REFERENCES Doctors(DoctorId),
        CONSTRAINT CK_Status CHECK (Status IN ('Pending', 'Confirmed', 'InProgress', 'Completed', 'Cancelled', 'NoShow')),
        CONSTRAINT CK_AppointmentTime CHECK (EndTime > AppointmentTime)
    );